// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwr47TR-F33li-5138j2peNr3FW7r4ITU',
    appId: '1:496623883580:web:0813a2604ce14adb7cba39',
    messagingSenderId: '496623883580',
    projectId: 'tubes-4245e',
    authDomain: 'tubes-4245e.firebaseapp.com',
    storageBucket: 'tubes-4245e.appspot.com',
    measurementId: 'G-9MZ6EYFCGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUHH6V8_oFEFvKuJeDFnWY_49Wy5VcoVs',
    appId: '1:496623883580:android:882dc2654bbeea237cba39',
    messagingSenderId: '496623883580',
    projectId: 'tubes-4245e',
    storageBucket: 'tubes-4245e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoQxSMbtf7daUhJoUP5F78MvW7QFf9y_A',
    appId: '1:496623883580:ios:5b33abc8e0b1ff6c7cba39',
    messagingSenderId: '496623883580',
    projectId: 'tubes-4245e',
    storageBucket: 'tubes-4245e.appspot.com',
    iosBundleId: 'com.example.projectPemob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoQxSMbtf7daUhJoUP5F78MvW7QFf9y_A',
    appId: '1:496623883580:ios:b1f708c4710746d17cba39',
    messagingSenderId: '496623883580',
    projectId: 'tubes-4245e',
    storageBucket: 'tubes-4245e.appspot.com',
    iosBundleId: 'com.example.projectPemob.RunnerTests',
  );
}
